version: '3'
services:
  frontend:
    build: frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
    command: sh -c 'cd app && yarn start'
    ports:
      - 3000:3000
    tty: true
  backend:
    build: backend
    # environment:
    volumes:
      - ./backend:/app
    ports:
      - 8000:80
    tty: true